# Generated by Django 3.1.7 on 2021-03-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210314_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='clientID',
            field=models.CharField(max_length=200),
        ),
    ]
