# Generated by Django 3.1.7 on 2021-03-14 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_tool_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='orderID',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
