# Generated by Django 3.1.7 on 2021-03-14 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rentalorder_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalorder',
            name='tool_name',
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.tool'),
        ),
    ]
