# Generated by Django 3.1.7 on 2021-03-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210314_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shippingstate',
            new_name='shippingprovince',
        ),
    ]
