# Generated by Django 3.1.7 on 2021-03-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
